"""
For each ORF, get_phasing determines P-site positions for all mapped reads and computes statistics for on-frame enrichment

usage:
python get_phasing.py --bam <bam-file> --orfs <ribofy orfs-file> --offsets <ribofy offsets-file> --output <output-file>

"""


import sys
import argparse
import pysam
import pandas as pd
import numpy as np
from tqdm import tqdm
from scipy.stats import wilcoxon, binomtest

from .utils import get_tid_info

def get_phasing (bamfile, orfs, offsets, output):

    print ("### get_phasing ###")

    print ("loading bam...")
    
    bam = pysam.Samfile (bamfile)

    dtid2count, dtid2ref = get_tid_info (bamfile)

    print ("loading offsets...")

    pd_offsets = pd.read_csv (offsets, sep="\t")

    header = {}

    # output file
    fout = open (output, "w")


    # checking orfs - line by line
    print ("checking orfs...")

    num_lines = sum(1 for line in open(orfs,'r'))

    with open(orfs, 'r') as f:

        for i, line in enumerate (tqdm(f, total=num_lines)):

            columns = line.strip ("\n").split ("\t")

            if i == 0:
                for icol, col in enumerate (columns):
                    header[col] = icol

                # printing output header
                print ("\t".join (columns + ["frame0", "frame1", "frame2", "p_wilcox", "p_binom"]), file=fout)
                continue
                
            bam_offsets = pd_offsets[pd_offsets.bam == bamfile]
            doffsets = bam_offsets[["read_length", "offset"]].set_index('read_length').to_dict ()['offset']
            
            tid, start, stop = dtid2ref[columns[header['tid']]], int(columns[header['start']]), int(columns[header['stop']])

            # print (tid, file=sys.stderr)

            cds = [0] * (stop-start+3)

            if len(cds)%3 != 0:
                print (f"ERROR: CDS-length invalid {tid}:{start}-{stop}")
                continue

            for read in bam.fetch (tid, start, stop):
                        
                read_length = read.infer_read_length () 
                
                if not read_length in doffsets:
                    continue

                length_offset = doffsets[read_length]
                
                offset_pos = read.pos + length_offset
                        
                if offset_pos >= start and offset_pos < stop+3: 
                    cds[offset_pos-start] += 1

            
            frame0 = [s for i, s in enumerate (cds) if i%3 == 0] # on-frame
            frame1 = [s for i, s in enumerate (cds) if i%3 == 1]
            frame2 = [s for i, s in enumerate (cds) if i%3 == 2]

            
            # wilcoxon-test for frame0 > mean (frame1, frame2)
            diff = np.array (frame0) - np.mean ([frame1, frame2], axis=0)            
            non_zero = np.sum(diff != 0)
            #mode = "exact" if non_zero <= 25 else "auto"            
            wilcox_stat, wilcox_p = wilcoxon(diff, alternative="greater") if non_zero >= 10 else (np.nan, np.nan)

            # binomial-test for n(frame0 > frame1 and frame > frame2)
            mat = np.concatenate ((frame0, frame1, frame2)).reshape ((-1,3), order='F')
            index_max = np.argmax (mat, axis=1)
            binom_test = binomtest (k=np.sum (index_max == 0), n=len(index_max), p=1/3, alternative="greater") # if non_zero >= 10 else (np.nan, np.nan)

            print ("\t".join (columns + [str(sum(frame0)), str(sum(frame1)), str(sum(frame2)), str(wilcox_p), str(binom_test.pvalue)]), file=fout)

    print ("done")


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='get phasing')
    parser.add_argument("--bam", dest='bam', required=True, help="Bam file - sorted and indexed")
    parser.add_argument("--orfs",   dest='orfs', required=True, help="orfs - generated by get_ORFs.py")
    parser.add_argument("--offsets", dest='offsets', required=True, help="offsets - generated by get_offsets.py")
    parser.add_argument("--output", dest='output', default = "ribofy_phasing.txt", help="output")
    args = parser.parse_args()

    get_phasing (args.bam, args.orfs, args.offsets, args.output)